### ISSUE TITLE
[Meta] Strings to-do list / after 1.0

### ISSUE THREAD

**Issue by dakaizou** [mozilla-mobile/FirefoxLite#950]
Build: 1563
Per the UX spec (Home: v2.1, Menu: v2.3)
Edited: 10/20 14:08
[Screenshots](https://conjuror.github.io/Zerda-Screenshots/index.html)
#### 0-1. Onboarding - first
- [x] "Thanks for choosing Firefox Rocket"
- [x] "A browser tailor-made for Indonesia by Mozilla, the non-profit committed to a free and open web."
- [x] "NEXT"
#### 0-2. Onboarding - second
- [x] "Browse faster than ever"
- [x] "Use turbo mode to block ads and trackers so you can browse at blazing speeds. If sites seems broken, just tap off the turbo mode switch in the menu."
- [x] "Turbo mode"
- [x] "NEXT"
#### 0-3. Onboarding - third
- [x] "Save data = Save money"
- [x] "Blocking ads and online trackers not only speeds up browsing, it saves data. Save even more when you block images."
- [x] "NEXT"
#### 0-4. Onboarding - forth
- [x] "Screenshot everything"
- [x] "Take screenshots of entire web pages. View a screenshot offline (without using data) or tap it to revisit the web page."
- [x] "OK, GOT IT!"
#### 1-1. Home | Long tap on top site
- [x] "Firefox Rocket"
- [x] "Search or enter address"
- [x] "Remove"
#### 1-2. Home | Menu
- [x] "Downloads"
- [x] "History"
- [x] "My shots"
- [x] "Turbo mode"
- [x] "Block image"
- [x] "Clear cache"
- [x] "Settings"
- [x] "Exit"
#### 2-1. HOME | Menu | Downloads empty
- [x] "No downloads"
#### 2-2-1. Home | Menu | Downloads with items
- [x] "CANCEL"
- [x] "downloading"
#### 2-2-2. Home | Menu | Downloads with items
- [x] "failed"
- [ ] _"canceled"_ (P 1.5)
- [x] "paused"
#### 2-2-3. Home | Menu | Downloads with items
- [x] "Pending"
- [x] "Unknown"
#### 2-3. Home | Menu | Downloads with items | item_menu
- [x] "Remove from list"
- [x] "Delete file"
#### 2-4. Home | Menu | Downloads with items | item_menu | Delete file
- [x] "file_name* was deleted" (snack bar - action: UNDO)
#### 2-5. Home | Menu | Downloads with items | tap on a missing file
- [x] "Cannot find the file" (toast)
#### 2-6. Home | Menu | Downloads with items | downloading_menu | CANCEL
- [x] "Download canceled" (toast)
#### 3-1. Home | Menu | History empty
- [x] "No browsing history"
#### 3-2. Home | Menu | History item | item menu (with CLEAR BROWSING HISTORY)
- [x] "CLEAR BROWSING HISTORY"
- [x] "Delete"
#### 3-3. Home | Menu | History item | CLEAR BROWSING HISTORY
- [x] "Clear all browsing history?"
- [x] "CANCEL"
- [x] "CLEAR"
#### 4-1. Home | Menu | My shots | No screenshots
- [x] "No Screenshots"
- [x] "Tap %capture_icon% on the menu to capture an entire web page."
#### 4-2. Home | Menu | My shots | Screenshot item | info
- [x] "Info"
- [x] "Date:"
- [x] "Resolution:"
- [x] "Size:"
- [x] "Title:"
- [x] "URL:"
- [x] "OK"
#### 4-3. Home | Menu | My shots | Screenshot item | Delete
- [x] "Delete this image?"
- [x] "CANCEL"
- [x] "DELETE"
#### 4-4. Home | Menu | My shots | Screenshot item | Delete | DELETE
- [x] "Screenshot deleted" (toast)
#### 4-5. Home | Menu | My shots | Tap on missing screenshot
- [x] "Cannot display the screenshot"
#### 5-1. Home | Menu | Turbo mode | -> off
- [x] "Turbo mode disabled" (toast)
#### 5-2. Home | Menu | Turbo mode | -> on
- [x] "Turbo mode enabled" (toast)
#### 6-1. Home | Menu | Block image | -> on
- [x] "Now showing images" (toast)
#### 6-2. Home | Menu | Block image | -> off
- [x] "Now blocking images" (toast)
#### 7-1-1. Home | Menu | Settings
- [x] "Language"
- [x] "Default search engine"
- [x] "Clear browsing data"
- [x] "Save downloads to"
- [x] "Turbo mode"
- [x] "Make default browser"
#### 7-1-2. Home | Menu | Settings
- [x] "Send usage data"
- [x] "Mozilla strives to collect only what we need to provide and improve Firefox Rocket for everyone."
- [x] "Learn more"
- [x] "Give feedback" (P 1.5)
- [x] "Share with friends" (P 1.5)
- [x] "About"
#### 7-2. Home | Menu | Settings | Language
- [x] "Language"
- [x] "System default"
- [x] "English"
- [x] "Indonesia" (or "Bahasa Indonesia", use system default)
- [x] "CANCEL"
#### 7-3. Home | Menu | Settings | Default search engine
- [x] "Default search engine"
- [x] "%current_default_search_engine%"
#### 7-4. Home | Menu | Settings | Clear browsing data
- [x] "Browsing history
- [x] "Form history"
- [x] "Cookies"
- [x] "Cache"
- [x] "CANCEL"
- [x] "CLEAR DATA"
#### 7-5. Home | Menu | Settings | Clear browsing data | CLEAR DATA
- [x] "Browsing data cleared" (toast)
#### 7-6. Home | Menu | Settings | Save downloads to
- [x] "Save downloads to"
- [x] "SD card"
- [x] "Internal storage"
- [x] "CANCEL"
#### 7-7. Home | Menu | Settings | Give feedback (P 1.5)
- [x] "Love Firefox Rocket?"
- [x] "Thank you for choosing our product. Your feedback is important to us."
- [x] "YES, RATE 5 STAR!"
- [x] "NO, SEND FEEDBACK."
#### 7-9-1. Home | Menu | Settings | Share with friends (P 1.5)
- [x] "Share Firefox Rocket with friends!"
- [x] "- Fast and lightweight"
- [x] "- Data saving"
- [x] "- Powerful screenshots"
- [x] "SHARE"
#### 7-9-2. Home | Menu | Settings | Share with friends | Share (P 1.5)
- [x] "Firefox Rocket"
- [x] "Hey, check out this fast and lightweight browser from Mozilla. Firefox Rocket https://mzl.la/2kScptw"
#### 7-10. Home | Menu | Settings | About
- [x] "Firefox Rocket is a fast and lightweight browser produced by Mozilla. Our mission is to foster a healthy, open internet."
- [x] "Learn more"
- [x] "Support"
- [x] "Your Rights / Licenses"
- [x] "Privacy Notice"
#### 7-11. Home | Menu | Settings | About | Your Rights
- [x] "Firefox Rocket is free and open source software made by Mozilla and other contributors."
- [x] "Firefox Rocket is made available to you under the terms of the Mozilla Public License and other open source licenses."
- [x] "You are not granted any rights or license to the trademarks of the Mozilla Foundation or any party, including the Mozilla, Firefox or Firefox Rocket names or logos. Additional information may be found here."
- [x] "Additional source code for Firefox Rocket is available under various other free and open source licenses."
- [x] "Firefox Rocket also uses blocklists provided by Disconnect, Inc. as separate and independent works under the GNU General Public Licence v3, and available here."
#### 8-1. Home | Menu | Clear cache
- [x] "%file_size% cache cleared" (toast)
#### 8-2. Home | Menu | Capture screenshot | Screenshot saved
- [x] "Screenshot saved" (snack bar - action: SHARE)
#### 8-3. Home | Menu | Capture screenshot | Failed to capture
- [x] "Failed to capture screenshot" (toast)
#### 8-4. Home | System screenshot (P 1.5)
- [x] "Tap the screenshot button in the menu to capture the whole page."
- [x] "Fast, easy and come back to the page at anytime!"
- [x] "GOT IT!"
#### 8-5. Home | Menu | Capture screenshot
- [x] "Capturing screenshot of entire page..."
#### 9-1. Home | Error page
- [x] "Webpage not available"
- [x] "- Make sure you are connected to the internet"
- [x] "- Check the address"
- [x] "TRY AGAIN"
#### 9-2. Home | Error page (app link)
- [x] "The address wasn’t understood"
- [x] "You might need to install other software to open this address."
- [x] "TRY AGAIN"
#### 9-3. Context menu inside Zerda
- [x] "Share link"
- [x] "Copy link address"
- [x] "Share image"
- [x] "Copy image address"
- [x] "Save image"
#### _9-5. Context menu inside Zerda | Download a file | Download using mobile data confirm (P 1.5)_
- [ ] _"file_name*"_
- [ ] _"filesize*"_
- [ ] _"Do you want to download the file over mobile connection?"_
- [ ] _"CANCEL"_
- [ ] _"YES"_
#### 9-6. Context menu inside Zerda | Download a file | Download started
- [x] "Downloading..." (toast)
#### 9-7. Context menu inside Zerda | Download a file | Download finished
- [x] "file_name* downloaded" (snack bar - action: OPEN)
#### _9-8. Context menu inside Zerda | Download a file | Download: No SD card detected_
- [ ] _"No SD card detected. File was saved to internal storage." (toast)_
#### _9-9. Context menu inside Zerda | Download a file | Download: Saved to SD card_
- [ ] _"File saved to SD card" (toast)_
#### 9-10. Context menu inside Zerda | Download a file | Download: SD card is full
- [x] "SD card is almost full. File was saved to internal storage." (toast)
#### 9-11. Context menu inside Zerda | Download a file | Download: Storage not available
- [x] "Storage inaccessible. Download canceled." (toast)
#### 9-12. Context menu inside Zerda | Download a file | Download: File type not supported
- [x] “File type not supported” (toast)
#### 9-13. Context menu inside Zerda | Download a file | Download: Protocol not supported
- [x] "Download protocol not supported" (toast)
#### 10-1. Context menu from outside app
- [x] "SEARCH IN FIREFOX ROCKET"

**Comment by chianger** [comment]
2-2-2 and 9-5 are P2.
Others let's do it before Oct-End.

**Comment by chianger** [comment]
To be clarified, there should be 9-8 9-9 9-10 in place but QA never able to see it. QAWAnted  to confirm.

**Comment by chianger** [comment]
2-4 should be done also. need QA verify.

**Comment by joechengla** [comment]
7-7 and 7-8 are the same. 7-8 should be removed

**Comment by joechengla** [comment]
8-4 screenshots contextual hints
Tap the screenshot button in the menu to capture the whole page. 
Fast, easy and come back to the page at anytime!

**Comment by joechengla** [comment]
7-9-2 Firefox Rocket url is https://mzl.la/2kScptw

**Comment by Jacklin-ux** [comment]
Add "Exit" button in menu, so please add this to copy string review.

**Comment by chianger** [comment]
adding milestone to track and make sure we get everything l10n.

**Comment by dakaizou** [comment]
## Translation needed
#### 1-2. Home | Menu
- [ ] "Exit"
#### 4-2. Home | Menu | My shots | Screenshot item | info
- [ ] "Date"
#### 7-7. Home | Menu | Settings | Give feedback (P 1.5)
- [ ] "Love Firefox Rocket?"
- [ ] "Thank you for choosing our product. Your feedback is important to us."
- [ ] "YES, RATE 5 STAR!"
- [ ] "NO, SEND FEEDBACK."
#### 7-9-1. Home | Menu | Settings | Share with friends (P 1.5)
- [ ] "Share Firefox Rocket with friends!"
- [ ] "- Fast and lightweight"
- [ ] "- Data saving"
- [ ] "- Powerful screenshots"
- [ ] "SHARE"
#### 7-9-2. Home | Menu | Settings | Share with friends | Share (P 1.5)
- [ ] "Firefox Rocket"
- [ ] "Hey, check out this fast and lightweight browser from Mozilla. Firefox Rocket https://mzl.la/2kScptw"
#### 8-4. Home | System screenshot (P 1.5)
- [ ] "Tap the screenshot button in the menu to capture the whole page."
- [ ] "Fast, easy and come back to the page at anytime!"
- [ ] "GOT IT!"

**Comment by brampitoyo** [comment]
## Translation
#### 1-2. Home | Menu
- [ ] "Tutup"
#### 4-2. Home | Menu | My shots | Screenshot item | info
- [ ] "Tanggal"
#### 7-7. Home | Menu | Settings | Give feedback (P 1.5)
- [ ] "Suka Firefox Rocket?"
- [ ] "Terima kasih telah memilih produk kami. Masukan anda sangat berarti."
- [ ] "YA, RATING BINTANG 5!"
- [ ] "TIDAK, KIRIM MASUKAN."
#### 7-9-1. Home | Menu | Settings | Share with friends (P 1.5)
- [ ] "Bagikan Firefox Rocket ke teman anda!"
- [ ] "- Cepat dan ringan"
- [ ] "- Hemat data"
- [ ] "- Tangkapan layar (screenshot) mumpuni"
- [ ] "BAGIKAN"
#### 7-9-2. Home | Menu | Settings | Share with friends | Share (P 1.5)
- [ ] "Firefox Rocket"
- [ ] "Coba browser baru dari Mozilla yang super cepat dan ringan. Firefox Rocket https://mzl.la/2kScptw"
#### 8-4. Home | System screenshot (P 1.5)
- [ ] "Ketuk tombol Tangkap laman untuk menangkap layar dari keseluruhan laman."
- [ ] "Cepat, mudah, dan gampang meninjau tangkapan layar kapan saja!"
- [ ] "MENGERTI!"

**Comment by chianger** [comment]
All features implemented have been confirmed with correct strings.
9-8 and 9-9 are non-reproducible so it's actually no user impact. 
We are keeping p2 tracking and some day we should probably remove the strings.

**Comment by cynthiatang** [comment]
It works in Rocket2.0
